### ISSUE TITLE
Directus 9.22.4 breaks /websocket route

### ISSUE THREAD

**Issue by cliqer** [br41nslug/directus-websocket-subscribe#14]
Directus 9.22.4 breaks /websocket route
```console
1|api  | 2023-01-12T13:50:34: [13:50:33.871] DEBUG: Route /websocket doesn't exist.
1|api  | 2023-01-12T13:50:34:     err: {
1|api  | 2023-01-12T13:50:34:       "type": "RouteNotFoundException",
1|api  | 2023-01-12T13:50:34:       "message": "Route /websocket doesn't exist.",
1|api  | 2023-01-12T13:50:34:       "stack":
1|api  | 2023-01-12T13:50:34:           Error: Route /websocket doesn't exist.
1|api  | 2023-01-12T13:50:34:               at notFound (/var/www/api/node_modules/directus/dist/controllers/not-found.js:31:14)
1|api  | 2023-01-12T13:50:34:       "status": 404,
1|api  | 2023-01-12T13:50:34:       "code": "ROUTE_NOT_FOUND",
1|api  | 2023-01-12T13:50:34:       "extensions": {}
1|api  | 2023-01-12T13:50:34:     }
```

**Comment by br41nslug** [comment]
I've just updated for `9.22.4` :) the rebuilt version seems to be working

**Comment by cliqer** [comment]
Thank you for that, but unfortunately, it doesn't; or it may be just me.
There must be a breaking change with the extension hooks and how they register as the WebSocket server opens and connects inbound to the server, but it doesn't outbound any data.
Try to subscribe from a client and change something on directus.

**Comment by br41nslug** [comment]
Does the extension load properly? and do you have any configurations that could be interfering?
![image](https://user-images.githubusercontent.com/9389634/212292701-9fb84149-e21d-47e1-bc75-2f4361449f03.png)

**Comment by cliqer** [comment]
Indeed, it was on my end.
After directus update/migrate, something got messed up and had to disable and re-enable the Permissions on the public role. Then everything came back to normal
