### ISSUE TITLE
Collection does not exist in schema

### ISSUE THREAD

**Issue by michalwolas** [br41nslug/directus-websocket-subscribe#18]
Hi 
I am trying to use this extension to get updates of items created in a collection over a web socket.

I used npm to install this extension.. 

I can connect to the websocket successfully but even with admin permissions I get "Collection does not exist in schema" 
![image](https://user-images.githubusercontent.com/68729715/226909771-7ebae6fe-279a-41fd-95fb-b562d982e183.png)
![image](https://user-images.githubusercontent.com/68729715/226910440-beb79183-19ba-4ac3-8fe7-f3facdfe3eaf.png)

I tried different collections but I get the same result. Any idea what could be causing this?

**Comment by cliqer** [comment]
That is because you are using uppercase for your collection names, and this extension only works with lowercase named collections.

**Comment by michalwolas** [comment]
would you know of any work-around, or is the only solution to re-name my table?

**Comment by cliqer** [comment]
Unfortunately, directus does not support renaming collections, and as such, you are left with two options:
1. Delete and recreate all your tables, making sure they are all lowercase
2. Try to figure out which part in this extension reads the collections, remove any 'tolowercase' references and then recompile.

Maybe someone has a better solution, though I couldn't find any and re-created the database.

**Comment by michalwolas** [comment]
![image](https://user-images.githubusercontent.com/68729715/226930474-b6e14cc9-f272-450a-bc67-a5467c732b62.png)
looks like its in src/utils.ts 
I removed the .toLowerCase() and now it recognizes my collection names.

**Comment by br41nslug** [comment]
Lol I do consider it bad practice to use capitalization in databases but hey I'm not  gonna start a new tabs vs spaces argument 😂
