### ISSUE TITLE
How can i custom payload answer

### ISSUE THREAD

**Issue by alexdieudonne** [br41nslug/directus-websocket-subscribe#3]
> Default i receive this

`` {
  "type": "SUBSCRIPTION",
  "action": "create",
  "payload": {
    "id": 1,
    "test": "test123",
  },
  "key": 1,
  "collection": "test"
}``

> but i want to show this
> I want to for example populate some field manually

`` {
  "type": "SUBSCRIPTION",
  "action": "create",
  "payload": {
    "id": {
          "name":"dqsqs",
          "email":"al223@gmail.com"
     },
    "test": "test123",
  },
  "key": 1,
  "collection": "test"
}``

**Comment by br41nslug** [comment]
Especially for the update event returning partial results i was missing such a feature myself too! So i finally got around to adding an event for doing such manipulations. More info can be found here :) https://github.com/br41nslug/directus-websocket-subscribe#subscription-filter

**Comment by alexdieudonne** [comment]
thank you !
